# Generated by Django 6.0.2 on 2026-02-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_lrn_userprofile_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='grade_level',
            field=models.CharField(choices=[('Pre-Kinder', 'Pre-Kinder'), ('Kinder', 'Kinder'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], max_length=20),
        ),
    ]
