# Generated by Django 6.0.1 on 2026-02-08 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_section_adviser_alter_adminprofile_permissions_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.IntegerField(help_text='0=Kinder, 1-6=Grade 1-6')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('category', models.CharField(choices=[('ACTIVITY', 'Activity'), ('QUIZ', 'Quiz'), ('EXAM', 'Exam')], max_length=10)),
                ('title', models.CharField(help_text='e.g. Activity 1, Quiz 3', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('date_given', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=100, help_text='Max possible score')),
                ('order', models.IntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to='accounts.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['quarter', 'category', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GradeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_weight', models.IntegerField(default=40, help_text='% for Activities')),
                ('quiz_weight', models.IntegerField(default=20, help_text='% for Quizzes')),
                ('exam_weight', models.IntegerField(default=20, help_text='% for Exams')),
                ('class_standing_weight', models.IntegerField(default=20, help_text='% for Class Standing')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade_weights', to='accounts.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('score', models.DecimalField(decimal_places=2, help_text='Score out of 100', max_digits=5)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'PARENT_STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='class_standings', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_standings', to='accounts.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='grades.gradeitem')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'PARENT_STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'grade_item')},
            },
        ),
    ]
