# Generated by Django 6.0.2 on 2026-02-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeweight',
            name='attendance_weight',
            field=models.IntegerField(default=10, help_text='% for Attendance'),
        ),
        migrations.AlterField(
            model_name='gradeweight',
            name='class_standing_weight',
            field=models.IntegerField(default=10, help_text='% for Class Standing'),
        ),
    ]
