# Generated by Django 6.0.1 on 2026-02-07 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_announcement_required_fields(apps, schema_editor):
    Announcement = apps.get_model("announcements", "Announcement")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    # 1) created_by: pick fallback user
    admin_user = User.objects.filter(is_superuser=True).first() or User.objects.first()
    if admin_user:
        Announcement.objects.filter(created_by__isnull=True).update(created_by=admin_user)

    # 2) publish_date: fill NULLs
    Announcement.objects.filter(publish_date__isnull=True).update(publish_date=timezone.now())

    # 3) title: fill NULLs or empty strings (if any)
    # If your old field allowed NULL, this prevents NOT NULL failure
    Announcement.objects.filter(title__isnull=True).update(title="Untitled")
    Announcement.objects.filter(title="").update(title="Untitled")


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_add_announcement_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ✅ Backfill old rows BEFORE enforcing NOT NULL constraints
        migrations.RunPython(backfill_announcement_required_fields, migrations.RunPython.noop),

        migrations.AlterField(
            model_name="announcement",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="publish_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="AnnouncementMedia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", models.FileField(upload_to="announcements/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("announcement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="media", to="announcements.announcement")),
            ],
        ),
    ]
