# Generated by Django 6.0.1 on 2026-02-07 13:01

import announcements.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmedia',
            name='file',
            field=models.FileField(upload_to='announcements/', validators=[announcements.models.validate_media_file_extension, announcements.models.validate_file_size]),
        ),
    ]
