# Generated by Django 6.0.2 on 2026-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcementmedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_role',
            field=models.CharField(choices=[('all', 'Public (All)'), ('teachers', 'Teachers'), ('parent_student', 'Parent / Student')], default='all', max_length=20),
        ),
    ]
