# Generated by Django 6.0.1 on 2026-02-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_section_adviser_alter_adminprofile_permissions_level_and_more'),
        ('enrollment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.section'),
        ),
    ]
