# Generated by Django 6.0.1 on 2026-02-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollment_address_enrollment_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
