# Generated by Django 6.0.1 on 2026-02-15 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_enrollment_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='education_level',
            field=models.CharField(blank=True, choices=[('preschool', 'Preschool'), ('elementary', 'Elementary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('installment', 'Installment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_type',
            field=models.CharField(blank=True, choices=[('new', 'New / Transferee'), ('old', 'Old Student')], max_length=10, null=True),
        ),
    ]
