# Generated by Django 6.0.1 on 2026-02-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_alter_enrollment_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
    ]
