# Generated by Django 6.0.2 on 2026-02-16 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_section_adviser_alter_adminprofile_permissions_level_and_more'),
        ('enrollment', '0009_enrollment_parent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='education_level',
            field=models.CharField(blank=True, choices=[('preschool', 'Preschool'), ('elementary', 'Elementary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade_level',
            field=models.CharField(choices=[('prek', 'Pre-Kinder'), ('kinder', 'Kinder'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('installment', 'Installment')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='accounts.section'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student_type',
            field=models.CharField(blank=True, choices=[('new', 'New / Transferee'), ('old', 'Old Student')], max_length=10, null=True),
        ),
    ]
