# Generated by Django 6.0.2 on 2026-02-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_alter_enrollment_education_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
